# Generated by Django 3.2.9 on 2022-02-02 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_title', models.CharField(default=None, help_text='Let your guest know details about this event', max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('event_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, default=None, max_length=15)),
                ('lng', models.FloatField(blank=True, default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(blank=True, default=None, max_length=150)),
                ('international_phone_number', models.CharField(blank=True, default=None, max_length=50)),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('place_id', models.CharField(blank=True, default=None, max_length=100)),
                ('rating', models.FloatField(blank=True, default=None, max_length=15)),
                ('user_rating_total', models.IntegerField(blank=True, default=None)),
                ('website', models.CharField(blank=True, default=None, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('geometry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.locationposition')),
            ],
        ),
    ]
