# Generated by Django 3.2.9 on 2022-01-14 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220114_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 19, 12, 43, 877751, tzinfo=utc), editable=False),
        ),
    ]
