# Generated by Django 3.2.9 on 2022-02-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_location_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.location'),
            preserve_default=False,
        ),
    ]
