# Generated by Django 3.2.9 on 2022-01-14 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 23, 53, 56, 199635, tzinfo=utc), editable=False),
        ),
    ]
