# Generated by Django 3.2.9 on 2022-01-15 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_Id',
            new_name='location_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 0, 10, 45, 488180, tzinfo=utc), editable=False),
        ),
    ]
