# Generated by Django 3.2.9 on 2022-02-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_event_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default=None, max_length=50)),
                ('author_url', models.URLField(blank=True, default=None)),
                ('profile_photo_url', models.URLField(blank=True, default=None)),
                ('rating', models.IntegerField(blank=True, default=None)),
                ('text', models.CharField(blank=True, default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_text', models.CharField(blank=True, default=None, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.workinghours'),
        ),
        migrations.AddField(
            model_name='location',
            name='photos',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.photos'),
        ),
        migrations.AddField(
            model_name='location',
            name='reviews',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.locationreview'),
        ),
    ]
