# Generated by Django 3.2.9 on 2022-02-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220202_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreview',
            name='relative_time_description',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='photos',
            name='height',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='photos',
            name='html_attributes',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='photos',
            name='width',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
