# Generated by Django 3.2.9 on 2022-01-15 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 0, 33, 29, 457044, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='extensions',
            field=models.ManyToManyField(blank=True, to='events.Extensions'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, to='events.Guest'),
        ),
    ]
