# Generated by Django 3.2.9 on 2022-01-15 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20220115_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 0, 43, 32, 94234, tzinfo=utc), editable=False),
        ),
    ]
