# Generated by Django 3.2.9 on 2022-02-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_photos_html_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='photos',
        ),
        migrations.AddField(
            model_name='location',
            name='photos',
            field=models.ManyToManyField(default=None, null=True, to='events.Photos'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='reviews',
        ),
        migrations.AddField(
            model_name='location',
            name='reviews',
            field=models.ManyToManyField(default=None, null=True, to='events.LocationReview'),
        ),
    ]
