# Generated by Django 3.2.9 on 2022-01-16 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 9, 1, 21, 885389, tzinfo=utc), editable=False),
        ),
    ]
