# Generated by Django 3.2.9 on 2022-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20220202_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photos',
            field=models.ManyToManyField(default=None, to='events.Photos'),
        ),
        migrations.AlterField(
            model_name='location',
            name='reviews',
            field=models.ManyToManyField(default=None, to='events.LocationReview'),
        ),
    ]
