# Generated by Django 3.2.9 on 2022-02-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0005_auto_20220205_1111'),
        ('events', '0009_auto_20220202_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.ManyToManyField(blank=True, to='extensions.Checklist')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('reminder', models.ManyToManyField(blank=True, to='extensions.Reminder')),
            ],
        ),
    ]
