# Generated by Django 3.2.9 on 2022-02-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='extension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.extension'),
            preserve_default=False,
        ),
    ]
