# Generated by Django 3.2.9 on 2022-02-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20220205_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.extension'),
        ),
    ]
