# Generated by Django 3.2.9 on 2022-02-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='reminder',
        ),
        migrations.AddField(
            model_name='extension',
            name='event',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
