# Generated by Django 3.2.9 on 2022-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220205_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='event',
        ),
    ]
