# Generated by Django 3.2.9 on 2022-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0007_auto_20220205_1451'),
        ('events', '0014_remove_extension_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extension',
        ),
    ]
