# Generated by Django 3.2.9 on 2021-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211122_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
    ]
