# Generated by Django 3.2.9 on 2022-02-04 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='items',
        ),
        migrations.AddField(
            model_name='checklist',
            name='items',
            field=models.ManyToManyField(to='extensions.ChecklistItems'),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='viewers',
        ),
        migrations.AddField(
            model_name='checklist',
            name='viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
