# Generated by Django 3.2.9 on 2022-02-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_auto_20220204_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitems',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
