# Generated by Django 3.2.9 on 2022-02-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_checklistitems_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling', models.DateTimeField(blank=True, default=None, null=True)),
                ('email_text', models.TextField(blank=True)),
            ],
        ),
    ]
