# Generated by Django 3.2.9 on 2022-02-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220205_1237'),
        ('extensions', '0005_auto_20220205_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='extension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.extension'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='extension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.extension'),
        ),
    ]
