# Generated by Django 3.2.9 on 2022-02-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_extension_event'),
        ('extensions', '0006_auto_20220205_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='extension',
        ),
        migrations.AddField(
            model_name='checklist',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
