# Generated by Django 3.2.9 on 2022-02-06 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0008_reminder_viewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='extension_owner',
            field=models.OneToOneField(default=19, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='extension_owner',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='checklist',
            name='viewers',
            field=models.ManyToManyField(to='extensions.Viewers'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='viewers',
            field=models.ManyToManyField(to='extensions.Viewers'),
        ),
    ]
