# Generated by Django 3.2.9 on 2022-02-06 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0009_auto_20220206_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='extension_owner',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='extension_owner',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Viewers',
        ),
    ]
