# Generated by Django 3.2.9 on 2022-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0010_auto_20220206_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extension',
        ),
        migrations.AddField(
            model_name='checklist',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
